#pragma once

// asdlfkjasdflkasdjfalsdkfjasdlfkjasdlfkjasdflkajsdflkajsdflkajsdflakjsdflaksjdflaksjdfalsdkfj
// asdlfkjasdflkasdjfalsdkfjasdlfkjasdlfkjasdflkajsdflkajsdflkajsdflakjsdflaksjdflaksjdfalsdkfj
// asdlfkjasdflkasdjfalsdkfjasdlfkjasdlfkjasdflkajsdflkajsdflkajsdflakjsdflaksjdflaksjdfalsdkfj
namespace foo {

void Foo();

}  // namespace foo